import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./normalize.css";

import "./globals.css";
import style from "./layaout.module.css";
import Header from "./components/Header/Header";
import FooterM from "./components/Footer/FooterM";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Наш проект",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="normalize.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@100;200;300;400;500;600;700;800;900&family=Nunito+Sans:wght@300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <div className={style.grid__wrapper}>
          <Header className={style.header}></Header>
          <aside className={style.sidebar}>sibebar</aside>
          <section className={style.body}>{children}</section>
          <FooterM className={style.footer}></FooterM>
        </div>
      </body>
    </html>
  );
}
